### ISSUE TITLE
PAR data

### ISSUE THREAD

**Issue by fscordo** [GLEON/LakeMetabolizer#133]
I am trying to work on the LakeMetabolyzer model. I have a question as regards the high-frequency data for PAR. We have a light sensor ( https://www.weatherhawk.com/product/signature-series-solar-radiation-sensor/ ) in a meteorological station in the lake. However, the wavelength the sensor measures a wavelength range from 300 to 1000 nm. So besides PAR, it is getting a portion of UV and a portion of Near-Infrared (but the sensor only gives me a single value in W/m2 for the whole wavelength range). Can you tell me what are your thoughts about using these values for the model? Is it correct if I use this value and informed that it compromises more than just PAR? Would I be overestimating PPR a lot?

**Comment by jzwart** [comment]
Hi @fscordo,
The model will fit with whatever irradiance you supply the model, whether that is PAR, shortwave radiation, etc... and in whatever units you supply the data (e.g. umol m-2 sec-1, W m-2). The most important thing is to keep the units and type of data (PAR, shortwave, etc...) the same across you daily model fits so that you can compare parameter fits across days. So you can fit your model with your data as is. I don't know if fitting the model with SW vs. PAR would make a difference, my instinct is that it won't affect model fit, but it would be good if there was a published comparison somewhere. 

Having said that, I think most people would consider the data your sensor is collecting as shortwave radiation. LakeMetabolizer has a function for converting from shortwave radiation to PAR with the function [sw.to.par](https://github.com/GLEON/LakeMetabolizer/blob/master/R/sw.to.par.R). This will convert from W/m2 to umol/m2/sec and you can fit the metabolism model using the converted light data.
